[package]
name = "advent_o_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
day_1 = { version = "0.1.0", path = "day_1" }
day_2 = { version = "0.1.0", path = "day_2" }
day_3 = { version = "0.1.0", path = "day_3" }
